### PR TITLE
Dependencies fixed

### PR DESCRIPTION
**Pull request by Jimut123**
Some dependencies were fixed, now it will work smoothly in Google Colab.

Here you may find the working version [https://colab.research.google.com/drive/1Wi1T6sUC_AkD2m3RcmexuUMKnonoJU9D?usp=sharing](https://colab.research.google.com/drive/1Wi1T6sUC_AkD2m3RcmexuUMKnonoJU9D?usp=sharing)

### CODE REVIEW

**Comment by AsmaBenBrahem** [comment]
This didn't work for me.
After executing:
! pip install -U --pre segmentation-models --user
! pip install keras==2.3.1
! pip uninstall tensorflow -y
! pip install tensorflow==2.2.0
than import keras but this caused an error saying: ModuleNotFoundError: No module named 'keras_applications' .

**Comment by Jimut123** [comment]
Weird, did you restart the environment?

**Comment by AsmaBenBrahem** [comment]
yes.
image
image

**Comment by Jimut123** [comment]
Lol, it is not working for me now, too... It was working a month back. Not sure. Closing PR.

**Pull request closed without merging**
